# Generated by Django 3.1 on 2020-11-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201109_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
