# Generated by Django 3.1 on 2020-11-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20201117_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
