# Generated by Django 3.1 on 2020-11-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
