# Generated by Django 3.1 on 2020-11-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
